//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lte.WinApp.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lte.WinApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 txt 的本地化字符串。
        /// </summary>
        internal static string DefaultCdrFileExt {
            get {
                return ResourceManager.GetString("DefaultCdrFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 csv 的本地化字符串。
        /// </summary>
        internal static string DefaultKpiFileExt {
            get {
                return ResourceManager.GetString("DefaultKpiFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 txt 的本地化字符串。
        /// </summary>
        internal static string DefaultMmlFileExt {
            get {
                return ResourceManager.GetString("DefaultMmlFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 xml 的本地化字符串。
        /// </summary>
        internal static string DefaultMrFileExt {
            get {
                return ResourceManager.GetString("DefaultMrFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 xlsx 的本地化字符串。
        /// </summary>
        internal static string DefaultParametersFileExt {
            get {
                return ResourceManager.GetString("DefaultParametersFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dat 的本地化字符串。
        /// </summary>
        internal static string DefaultRuFileExt {
            get {
                return ResourceManager.GetString("DefaultRuFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似       通过输入经纬度等信息，查询相应的DT数据记录内容，测试查询数据库程序的正确性。  的本地化字符串。
        /// </summary>
        internal static string MainMenu_DtDisplayContents {
            get {
                return ResourceManager.GetString("MainMenu_DtDisplayContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看DT数据内容 的本地化字符串。
        /// </summary>
        internal static string MainMenu_DtDisplayTitle {
            get {
                return ResourceManager.GetString("MainMenu_DtDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似       导入全天掉话性能以及相关详细信息、原因分析和4G精确覆盖率等指标分布。 的本地化字符串。
        /// </summary>
        internal static string MainMenu_KpiImportComments {
            get {
                return ResourceManager.GetString("MainMenu_KpiImportComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每日指标信息导入 的本地化字符串。
        /// </summary>
        internal static string MainMenu_KpiImportTitle {
            get {
                return ResourceManager.GetString("MainMenu_KpiImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似       通过Excel表导入全网或部分基站、小区信息。首先从Excel表和MML文件中读入LTE和CDMA的工参信息，然后将基站、小区和共站信息导入到数据库中。 的本地化字符串。
        /// </summary>
        internal static string MainMenu_ParametersComments {
            get {
                return ResourceManager.GetString("MainMenu_ParametersComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础数据导入 的本地化字符串。
        /// </summary>
        internal static string MainMenu_ParametersTitle {
            get {
                return ResourceManager.GetString("MainMenu_ParametersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似       MRS和MRO数据导入，用于简要数据库内容测试，以验证后续网页程序应用。 的本地化字符串。
        /// </summary>
        internal static string MainMenu_RuMrDisplayComments {
            get {
                return ResourceManager.GetString("MainMenu_RuMrDisplayComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MR数据导入 的本地化字符串。
        /// </summary>
        internal static string MainMenu_RuMrDisplayTitle {
            get {
                return ResourceManager.GetString("MainMenu_RuMrDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似       导入RU二进制记录及简要话单文件，用于后续4G站点规划分析，生成规划负面清单。 的本地化字符串。
        /// </summary>
        internal static string MainMenu_RutraceImportComments {
            get {
                return ResourceManager.GetString("MainMenu_RutraceImportComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RU及简要话单文件导入 的本地化字符串。
        /// </summary>
        internal static string MainMenu_RutraceImportTitle {
            get {
                return ResourceManager.GetString("MainMenu_RutraceImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开CDMA工参文件 的本地化字符串。
        /// </summary>
        internal static string OpenCdmaFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenCdmaFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简要话单文件|*.txt 的本地化字符串。
        /// </summary>
        internal static string OpenCdrFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenCdrFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开简要话单文件 的本地化字符串。
        /// </summary>
        internal static string OpenCdrFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenCdrFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每日指标文件|*.csv 的本地化字符串。
        /// </summary>
        internal static string OpenKpiFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenKpiFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开每日指标文件 的本地化字符串。
        /// </summary>
        internal static string OpenKpiFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenKpiFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开LTE工参文件 的本地化字符串。
        /// </summary>
        internal static string OpenLteFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenLteFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LTE邻区关系定义文件|*.csv 的本地化字符串。
        /// </summary>
        internal static string OpenLteNeighborDialogFilter {
            get {
                return ResourceManager.GetString("OpenLteNeighborDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开LTE邻区关系定义文件 的本地化字符串。
        /// </summary>
        internal static string OpenLteNeighborDialogTitle {
            get {
                return ResourceManager.GetString("OpenLteNeighborDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MML文件|*.txt 的本地化字符串。
        /// </summary>
        internal static string OpenMmlFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenMmlFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开MML文件 的本地化字符串。
        /// </summary>
        internal static string OpenMmlFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenMmlFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MR记录文件|*.xml 的本地化字符串。
        /// </summary>
        internal static string OpenMrFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenMrFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开MR XML文件 的本地化字符串。
        /// </summary>
        internal static string OpenMrFileDialogTiltle {
            get {
                return ResourceManager.GetString("OpenMrFileDialogTiltle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工参文件|*.xls;*.xlsx 的本地化字符串。
        /// </summary>
        internal static string OpenParametersFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenParametersFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 精确覆盖指标文件|*.csv 的本地化字符串。
        /// </summary>
        internal static string OpenPreciseFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenPreciseFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开精确覆盖指标文件 的本地化字符串。
        /// </summary>
        internal static string OpenPreciseFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenPreciseFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RU二进制文件|*.dat 的本地化字符串。
        /// </summary>
        internal static string OpenRuFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenRuFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开RU二进制文件 的本地化字符串。
        /// </summary>
        internal static string OpenRuFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenRuFileDialogTitle", resourceCulture);
            }
        }
    }
}
